[style_train_config]
num_epoch = 40
max_norm = 10
dt = 0.1
device = "auto"
best_model_path_template = "models/best-model-{timestamp}.pth"
loss_func = "StyleLoss.acc_spacing_mse"
optim = "Adam"
lr = 0.0005

[style_train_config.logger]
mode = "normal"
